language: node_js
node_js:
    - 6
install:
|
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
script:
    - npm run test
after_script:
    - npm run coveralls
after_success:
    - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls

